
spring:
  mail:
    host: smtp.aliyun.com
    username: jionjion@aliyun.com
    password: XXX
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    default-encoding: UTF-8