# 激活文件

# Spring配置信息
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot_study?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: default


# Mybatis的配置信息
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.jionjion.web.bean


# 容器配置信息
context:
  # 初始化器
  initializer:
    classes: top.jionjion.core.initializer.WebApplicationInitializerThird
  # 监听器
  listener:
    classes: top.jionjion.core.listener.WebApplicationListenerThird

# 日志配置
trace: true
logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-60.60logger#%M{50}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  level:
    root: trace


# 使用自定义的 starter
weather:
  enable: true
  type: 下雪
  rate: 严重
