# 流水线名称
name: Auto Build And Analyze

# 触发条件
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# 任务明细
jobs:
  build:
    # 运行环境
    runs-on: ubuntu-latest
    # 步骤
    steps:
      # 1. 检出
      - uses: actions/checkout@v3
      # 2. 设置JDK 环境
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      # 3. 批次构建
      - name: Build with Maven [top.jionjion:version]
        run: mvn -B install -DskipTests -s ./github/configs/settings.xml --file version/pom.xml
      - name: Build with Maven [top.jionjion:caching]
        run: mvn -B package -DskipTests -s ./github/configs/settings.xml --file caching/pom.xml



      # 2. 初始化 CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'java'

      # 5. 语法分析
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
