# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

# 流水线名称
name: Java CI with Maven

# 触发条件
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# 任务明细
jobs:
  build:
    # 运行环境
    runs-on: ubuntu-latest
    # 步骤
    steps:
    # 1. 检出
    - uses: actions/checkout@v3
    # 2. 设置JDK 环境
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    # 3.1 单个构建
    - name: Build with Maven [top.jionjion:version]
      run: mvn -B install -DskipTests -s ./.github/settings/settings.xml --file version/pom.xml
    # 3.2 批次构建
    - name: Build with Maven [top.jionjion]
      run: |
        chmod +x ./.github/scripts/maven-build.sh &&
        ./.github/scripts/maven-build.sh